# Generated by Django 5.2.6 on 2025-09-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text="El ID único del video de YouTube (ej: 'dQw4w9WgXcQ')", max_length=20, unique=True)),
                ('title', models.CharField(help_text='Un título para identificar el partido', max_length=200)),
                ('match_type', models.CharField(choices=[('RIVAL', 'Análisis de Rivales'), ('TEAM', 'Análisis Propio')], default='RIVAL', help_text='Define el tipo de análisis para este partido', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='RivalPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_name', models.CharField(max_length=255, verbose_name='Row Name')),
                ('clip_start', models.FloatField(help_text='Segundo de inicio del clip', verbose_name='Clip Start')),
                ('clip_end', models.FloatField(help_text='Segundo de fin del clip', verbose_name='Clip End')),
                ('jersey', models.IntegerField(blank=True, null=True, verbose_name='JERSEY')),
                ('player_id', models.CharField(blank=True, max_length=100, verbose_name='PlayerID')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='NOMBRE')),
                ('equipo', models.CharField(blank=True, max_length=255, verbose_name='EQUIPO')),
                ('team_id', models.CharField(blank=True, max_length=100, verbose_name='TeamID')),
                ('fecha', models.CharField(blank=True, max_length=100, verbose_name='FECHA')),
                ('tantos', models.IntegerField(blank=True, null=True, verbose_name='TANTOS')),
                ('resultado', models.CharField(blank=True, max_length=255, verbose_name='RESULTADO')),
                ('action', models.CharField(blank=True, max_length=255, verbose_name='ACTION')),
                ('axis_tiempo', models.CharField(blank=True, max_length=100, verbose_name='AXIS TIEMPO')),
                ('axis_x', models.FloatField(blank=True, null=True, verbose_name='AXIS X')),
                ('axis_y', models.FloatField(blank=True, null=True, verbose_name='AXIS Y')),
                ('end', models.CharField(blank=True, max_length=255, verbose_name='END')),
                ('try_orig', models.CharField(blank=True, max_length=255, verbose_name='TRYORIG')),
                ('li_for', models.CharField(blank=True, max_length=255, verbose_name='LIFOR')),
                ('li_type', models.CharField(blank=True, max_length=255, verbose_name='LITYPE')),
                ('li_place', models.CharField(blank=True, max_length=255, verbose_name='LIPLACE')),
                ('li_jumper', models.CharField(blank=True, max_length=255, verbose_name='LIJUMPER')),
                ('li_delivery', models.CharField(blank=True, max_length=255, verbose_name='LIDELIVERY')),
                ('time', models.CharField(blank=True, max_length=100, verbose_name='TIME')),
                ('mins', models.IntegerField(blank=True, null=True, verbose_name='Mins')),
                ('ruck_start', models.FloatField(blank=True, null=True, verbose_name='RUCKSTART')),
                ('ruck_end', models.FloatField(blank=True, null=True, verbose_name='RUCKEND')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rival_plays', to='player.match')),
            ],
            options={
                'verbose_name': 'Jugada de Rival',
                'verbose_name_plural': 'Jugadas de Rivales',
            },
        ),
    ]
