# Generated by Django 5.2.6 on 2025-09-24 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Equipo')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Alias/Nombre abreviado')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(db_index=True, max_length=100, verbose_name='Equipo Local')),
                ('away_team', models.CharField(db_index=True, max_length=100, verbose_name='Equipo Visitante')),
                ('video_id', models.CharField(help_text='El ID único del video de YouTube', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('match_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha del Partido')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_teams_distinct'), models.UniqueConstraint(fields=('home_team', 'away_team', 'match_date'), name='match_unique_teams_date')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('COACH', 'Entrenador'), ('PLAYER', 'Jugador')], default='COACH', max_length=10, verbose_name='Rol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugada', models.CharField(blank=True, max_length=255, verbose_name='Jugada')),
                ('arbitro', models.CharField(blank=True, max_length=255, verbose_name='Arbitro')),
                ('canal_inicio', models.CharField(blank=True, max_length=100, verbose_name='Canal Inicio')),
                ('evento', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Evento')),
                ('equipo', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Equipo')),
                ('fin', models.DecimalField(decimal_places=3, help_text='Segundo exacto de fin (ms)', max_digits=9, verbose_name='Fin (segundos)')),
                ('ficha', models.CharField(blank=True, max_length=100, verbose_name='Ficha')),
                ('inicia', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Inicia')),
                ('inicio', models.DecimalField(decimal_places=3, help_text='Segundo exacto de inicio (ms)', max_digits=9, verbose_name='Inicio (segundos)')),
                ('resultado', models.CharField(blank=True, max_length=100, verbose_name='Resultado')),
                ('termina', models.CharField(blank=True, max_length=100, verbose_name='Termina')),
                ('tiempo', models.CharField(blank=True, max_length=50, verbose_name='Tiempo')),
                ('torneo', models.CharField(blank=True, max_length=255, verbose_name='Torneo')),
                ('zona_fin', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Zona Fin')),
                ('zona_inicio', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Zona Inicio')),
                ('jugadores', models.CharField(blank=True, max_length=255, verbose_name='Jugadores')),
                ('sigue_con', models.CharField(blank=True, max_length=255, verbose_name='Sigue Con')),
                ('pos_tiro', models.CharField(blank=True, max_length=100, verbose_name='Pos Tiro')),
                ('set', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Set')),
                ('tiro', models.CharField(blank=True, max_length=100, verbose_name='Tiro')),
                ('tipo', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Tipo')),
                ('accion', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Accion')),
                ('termina_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Termina En')),
                ('sancion', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Sancion')),
                ('situacion', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Situacion')),
                ('transicion', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Transicion')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='player.match')),
            ],
            options={
                'verbose_name': 'Jugada',
                'verbose_name_plural': 'Jugadas',
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['match', 'inicio'], name='idx_play_match_inicio'), models.Index(fields=['evento'], name='idx_play_evento'), models.Index(fields=['equipo'], name='idx_play_equipo'), models.Index(fields=['zona_inicio'], name='idx_play_zona_inicio'), models.Index(fields=['zona_fin'], name='idx_play_zona_fin'), models.Index(fields=['inicia'], name='idx_play_inicia'), models.Index(fields=['situacion'], name='idx_play_situacion'), models.Index(fields=['tipo'], name='idx_play_tipo'), models.Index(fields=['accion'], name='idx_play_accion'), models.Index(fields=['termina_en'], name='idx_play_termina_en'), models.Index(fields=['sancion'], name='idx_play_sancion'), models.Index(fields=['transicion'], name='idx_play_transicion')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gte', models.F('inicio'))), name='play_fin_gte_inicio'), models.CheckConstraint(condition=models.Q(('inicio__gte', 0)), name='play_inicio_gte_0'), models.CheckConstraint(condition=models.Q(('fin__gte', 0)), name='play_fin_gte_0')],
            },
        ),
    ]
