# Generated by Django 5.2.6 on 2025-09-17 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='Equipo Local')),
                ('away_team', models.CharField(max_length=100, verbose_name='Equipo Visitante')),
                ('video_id', models.CharField(help_text='El ID único del video de YouTube', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.FloatField(help_text='Segundo exacto de inicio', verbose_name='INICIO (segundos)')),
                ('fin', models.FloatField(help_text='Segundo exacto de fin', verbose_name='FIN (segundos)')),
                ('arbitro', models.CharField(blank=True, max_length=255, verbose_name='Arbitro')),
                ('canal_inicio', models.CharField(blank=True, max_length=100, verbose_name='CANAL INICIO')),
                ('evento', models.CharField(blank=True, max_length=255, verbose_name='EVENTO')),
                ('equipo', models.CharField(blank=True, max_length=255, verbose_name='Equipo')),
                ('ficha', models.CharField(blank=True, max_length=100, verbose_name='Ficha')),
                ('inicia', models.CharField(blank=True, max_length=100, verbose_name='INICIA')),
                ('resultado', models.CharField(blank=True, max_length=100, verbose_name='Resultado')),
                ('termina', models.CharField(blank=True, max_length=100, verbose_name='TERMINA')),
                ('tiempo', models.CharField(blank=True, max_length=50, verbose_name='TIEMPO')),
                ('torneo', models.CharField(blank=True, max_length=255, verbose_name='Torneo')),
                ('zona_fin', models.CharField(blank=True, max_length=100, verbose_name='ZONA FIN')),
                ('zona_inicio', models.CharField(blank=True, max_length=100, verbose_name='ZONA INICIO')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='player.match')),
            ],
            options={
                'verbose_name': 'Jugada',
                'verbose_name_plural': 'Jugadas',
            },
        ),
    ]
