# Generated by Django 5.2.6 on 2025-11-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='País')),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='ISO (2/3)')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='division',
            field=models.CharField(blank=True, choices=[('PRIMERA', 'Primera'), ('RESERVA', 'Reserva'), ('PRE_A', 'Pre A'), ('PRE_B', 'Pre B')], db_index=True, max_length=20, null=True, verbose_name='División'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Torneo')),
                ('season', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Temporada')),
                ('level', models.CharField(blank=True, max_length=100, verbose_name='Nivel/Categoría')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre corto')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='player.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='player.tournament', verbose_name='Torneo'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name', 'country', 'season'), name='uniq_tournament_country_season'),
        ),
    ]
