# Generated by Django 5.2.6 on 2025-09-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at'], 'verbose_name': 'Partido', 'verbose_name_plural': 'Partidos'},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['inicio'], 'verbose_name': 'Jugada', 'verbose_name_plural': 'Jugadas'},
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha del Partido'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Equipo Visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Equipo Local'),
        ),
        migrations.AlterField(
            model_name='play',
            name='equipo',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='play',
            name='evento',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='EVENTO'),
        ),
        migrations.AlterField(
            model_name='play',
            name='fin',
            field=models.DecimalField(decimal_places=3, help_text='Segundo exacto de fin (ms)', max_digits=9, verbose_name='FIN (segundos)'),
        ),
        migrations.AlterField(
            model_name='play',
            name='inicia',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='INICIA'),
        ),
        migrations.AlterField(
            model_name='play',
            name='inicio',
            field=models.DecimalField(decimal_places=3, help_text='Segundo exacto de inicio (ms)', max_digits=9, verbose_name='INICIO (segundos)'),
        ),
        migrations.AlterField(
            model_name='play',
            name='zona_fin',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ZONA FIN'),
        ),
        migrations.AlterField(
            model_name='play',
            name='zona_inicio',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ZONA INICIO'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['match', 'inicio'], name='idx_play_match_inicio'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['evento'], name='idx_play_evento'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['equipo'], name='idx_play_equipo'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['zona_inicio'], name='idx_play_zona_inicio'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['zona_fin'], name='idx_play_zona_fin'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['inicia'], name='idx_play_inicia'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='match_teams_distinct'),
        ),
        migrations.AddConstraint(
            model_name='play',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gte', models.F('inicio'))), name='play_fin_gte_inicio'),
        ),
        migrations.AddConstraint(
            model_name='play',
            constraint=models.CheckConstraint(condition=models.Q(('inicio__gte', 0)), name='play_inicio_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='play',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gte', 0)), name='play_fin_gte_0'),
        ),
    ]
