# Generated by Django 5.2.6 on 2025-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='marcador_final',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marcador Final'),
        ),
    ]
