# Generated by Django 5.2.6 on 2025-09-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_match_options_alter_play_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='accion',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ACCION'),
        ),
        migrations.AddField(
            model_name='play',
            name='jugadores',
            field=models.CharField(blank=True, max_length=255, verbose_name='JUGADORES'),
        ),
        migrations.AddField(
            model_name='play',
            name='pos_tiro',
            field=models.CharField(blank=True, max_length=100, verbose_name='POS TIRO'),
        ),
        migrations.AddField(
            model_name='play',
            name='sancion',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='SANCION'),
        ),
        migrations.AddField(
            model_name='play',
            name='set_play',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='SET'),
        ),
        migrations.AddField(
            model_name='play',
            name='sigue_con',
            field=models.CharField(blank=True, max_length=255, verbose_name='SIGUE CON'),
        ),
        migrations.AddField(
            model_name='play',
            name='situacion',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='SITUACION'),
        ),
        migrations.AddField(
            model_name='play',
            name='termina_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='TERMINA EN'),
        ),
        migrations.AddField(
            model_name='play',
            name='tipo',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='TIPO'),
        ),
        migrations.AddField(
            model_name='play',
            name='tiro',
            field=models.CharField(blank=True, max_length=100, verbose_name='TIRO'),
        ),
        migrations.AddField(
            model_name='play',
            name='transicion',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='TRANSICION'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['situacion'], name='idx_play_situacion'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['tipo'], name='idx_play_tipo'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['accion'], name='idx_play_accion'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['termina_en'], name='idx_play_termina_en'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['sancion'], name='idx_play_sancion'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['transicion'], name='idx_play_transicion'),
        ),
    ]
