# Generated by Django 5.2.6 on 2025-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_country_match_division_tournament_match_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Torneo abreviado (siglas)'),
        ),
    ]
