# Generated by Django 5.2.6 on 2025-11-27 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_tournament_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachTournamentTeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(db_index=True, max_length=20, verbose_name='Temporada')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_participations', to='player.team', verbose_name='Equipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_participations', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador')),
            ],
            options={
                'verbose_name': 'Participación de Entrenador (Temporada)',
                'verbose_name_plural': 'Participaciones de Entrenadores (Temporada)',
                'ordering': ['user__username', 'season', 'team__name'],
                'unique_together': {('user', 'season', 'team')},
            },
        ),
    ]
