# Generated by Django 5.2.6 on 2025-09-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_play_accion_play_jugadores_play_pos_tiro_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('home_team', 'away_team', 'match_date'), name='match_unique_teams_date'),
        ),
    ]
