# Generated by Django 5.2.6 on 2026-02-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_gpsmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpsmetric',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
