# Generated by Django 5.2.6 on 2026-02-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_alter_gpsmetric_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='canal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='play',
            name='desde',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='play',
            name='fases',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fases'),
        ),
    ]
