# Generated by Django 5.2.6 on 2026-02-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_play_canal_play_desde_play_fases'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='opcion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Opción'),
        ),
        migrations.AddField(
            model_name='play',
            name='zona',
            field=models.CharField(blank=True, max_length=100, verbose_name='Zona'),
        ),
    ]
