# Generated by Django 5.2.6 on 2026-04-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('PLAYER', 'Jugador'), ('COACH', 'Entrenador')], default='PLAYER', max_length=10, verbose_name='Rol a asignar'),
        ),
    ]
