# Generated by Django 5.2.6 on 2026-04-13 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_add_role_to_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('home_team', models.CharField(max_length=100, verbose_name='Equipo Local')),
                ('away_team', models.CharField(max_length=100, verbose_name='Equipo Visitante')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Sede / Cancha')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles Local')),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles Visitante')),
                ('is_played', models.BooleanField(db_index=True, default=False, verbose_name='¿Jugado?')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_matches', to='player.tournament', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Partido Agendado',
                'verbose_name_plural': 'Partidos Agendados',
                'ordering': ['date', 'time'],
            },
        ),
    ]
