# Generated by Django 5.2.6 on 2026-04-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_add_scheduled_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntos Visitante'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puntos Local'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sede / Cancha'),
        ),
        migrations.AlterField(
            model_name='match',
            name='video_id',
            field=models.CharField(blank=True, help_text='El ID único del video de YouTube', max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ScheduledMatch',
        ),
    ]
