# Generated by Django 5.2.6 on 2026-04-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_unify_match_scheduled_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='venue',
        ),
    ]
