"""
Django settings for rugby_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-rj(y$$3w@t4%1cm*v6$#hzsn%^1)7b&(6^hv7a-8_8lk7vi-f=')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Comma-separated list, e.g. "example.com,api.example.com"
_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '').strip()
# Si la variable DJANGO_ALLOWED_HOSTS no está definida:
#  - en desarrollo permitimos localhost
#  - en producción podrías querer fallar; opcionalmente se agrega '.run.app' para Cloud Run
# Recomendado: definir DJANGO_ALLOWED_HOSTS="localhost,127.0.0.1,rugby-app-50727258277.southamerica-east1.run.app" (o tu dominio personalizado)
parsed_hosts = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
if not parsed_hosts:
    # Fallback seguro para dev; en Cloud Run añadimos automáticamente el comodín .run.app
    parsed_hosts = ['localhost', '127.0.0.1']
    if 'K_SERVICE' in os.environ:  # Estamos en Cloud Run
        parsed_hosts.append('.run.app')  # acepta cualquier servicio *.run.app
ALLOWED_HOSTS = parsed_hosts

# Comma-separated with scheme, e.g. "https://example.com,https://api.example.com"
_csrf_origins = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').strip()
_parsed_csrf = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
if not _parsed_csrf:
    # Dev defaults; para producción añade tu dominio con https
    _parsed_csrf = [
        'http://127.0.0.1:8000',
        'http://localhost:8000',
    ]
    # Ejemplo para Cloud Run (ajusta al host real):
    # _parsed_csrf.append('https://rugby-app-50727258277.southamerica-east1.run.app')
CSRF_TRUSTED_ORIGINS = _parsed_csrf


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'player',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',  # auth por JWT (opcional)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise solo en producción; evita fallos en local si no está instalado
    # Se inyecta más abajo si DEBUG es False
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    # Insertar WhiteNoise inmediatamente después de SecurityMiddleware
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'rugby_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rugby_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # Permite override por variables de entorno para Cloud SQL / proxy
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'rugby_player_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', '141304'),
        # Para Cloud SQL Auth Proxy en local: HOST=127.0.0.1, PORT=5433
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# rugby_project/settings.py

# Archivos estáticos (CSS, JavaScript, Imágenes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Estáticos del proyecto en desarrollo
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')    # Donde collectstatic los recopila (para prod)
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Archivos subidos por usuarios
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Directorio donde se guardan los archivos
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cloud Run / reverse proxy: confiar en cabecera de protocolo para HTTPS
# Evita redirecciones incorrectas y asegura que request.is_secure() funcione tras el proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}
